location                = "westeurope"
prefix                  = "sb"
environment             = "dev"
name                    = "sbops"
#vnet properties
resource_group_name     = "sbops-tf-rg"
network_address_space = "192.168.0.0/16"
sbops_subnet_address_name = "sbops"
sbops_subnet_address_prefix = "192.168.0.0/24"
subnet_address_name = "appgw"
subnet_address_prefix = "192.168.1.0/24"